---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/kukaraf/devpod
name: devpod
description: Personal Fedora Silverblue image.

labels:
  ostree.bootable: "true"

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: gschema-overrides
    include:
      - zz1-defaults.gschema.override

  - type: bling
    install:
      - dconf-update-service

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://cli.github.com/packages/rpm/gh-cli.repo
    install:
      - tailscale
      - gh
      - stow
      - btop
      - distrobox
      - syncthing
      - fzf
      - steam-devices
      - gcc
      - gcc-c++
      - python3-devel

  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
          name: flathub
        install:
          - io.github.v81d.Wattage
          - com.ranfdev.DistroShelf
          - md.obsidian.Obsidian
          - it.mijorus.gearlever
          - app.grayjay.Grayjay
          - net.codelogistics.webapps
          - com.rioterm.Rio
          - com.valvesoftware.Steam
          - de.haeckerfelix.Shortwave
          - com.mattjakeman.ExtensionManager
          - io.mpv.Mpv
          - com.github.xournalpp.xournalpp
          - org.localsend.localsend_app
          - de.haeckerfelix.Fragments
      - scope: system
        repo:
          url: https://registry.fedoraproject.org
          name: fedora
        install:
          - org.keepassxc.KeePassXC

  - type: script
    no-cache: true
    scripts:
      - install-uv-tools.sh

  - type: signing
