read:
  - CONVENTIONS.md

vim: false
detect-urls: true
#model: codestral/codestral-latest
#model: groq/openai/gpt-oss-120b
#model: openrouter/moonshotai/kimi-k2-thinking
model: groq/moonshotai/kimi-k2-instruct-0905
timeout: 30
cache-prompts: true
show-diffs: true
git-commit-verify: true
no-auto-commits: true
weak-model: groq/openai/gpt-oss-20b
