dark-mode: true

model: openrouter/deepseek/deepseek-v3.2-exp
cache-prompts: true
show-diffs: true
commit-prompt: "generate a commit message for the following changes, describe why the changes are beeing performed (not what is beeing done) make sure to be short and to the point e.g. refactor: cleanup old unnecesarry code OR Cange: button to blue as per client request"
weak-model: moonshotai/kimi-k2-0905
