read:
  - CONVENTIONS.md
vim: false
detect-urls: true
model: groq/moonshotai/kimi-k2-instruct-0905
timeout: 30
cache-prompts: true
show-diffs: true
no-auto-commits: true
weak-model: groq/openai/gpt-oss-20b
