[font]
size = 12

[font.bold]
family = "0xProto Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font Propo"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Propo"
style = "Regular"

[window]
opacity = 0.8
